import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { DateInput } from "../Components/Date/Date";
import { Title } from "../Components/Title/Title";
import { Button } from "@nextui-org/react";
import { useState } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [selectedDate, setSelectedDate] = useState<string>();

  const handleChange = (value: any) => {
    const day = new Date(value).getDate()
    const month = new Date(value).getMonth()
    const year = new Date(value).getFullYear()
    setSelectedDate(`${day}-${month}-${year}`)
  }; 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <Title title={"Seleccione una Fecha"} />
        <DateInput handleChange={handleChange} />
        <Link href={`/turnos/${selectedDate}`} className="link">
          <Button
            color="gradient"
            auto
            className={styles.button}
            disabled={!selectedDate}
          >
            Continuar
          </Button>
        </Link>
      </div>
    </>
  );
}
