import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Fecha} from '../Components/Fecha/Fecha';
import {Button} from '@nextui-org/react';
import { Example } from '../Components/Example/Example';
import { MyModal } from '../Components/Modal/Modal';

const inter = Inter({ subsets: ['latin'] })


export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       
        <Button color='gradient'>Click me </Button>
      
        <MyModal/>
      </main>
    </>
  )
}
