import { Turno } from "@/src/models/turnos";

export const TURNOS_DISPONIBLES:Turno[] = [
    {
      id: 1,
      completed: true,
      date: '11/10/23',
      timeType: 'MAÑANA',
      start_time: '08:00',
      end_time: '09:00',
    },
    {
      id: 2,
      completed: false,
      date: '11/10/23',
      timeType: 'MAÑANA',
      start_time: '09:00',
      end_time: '10:00',
    },
    {
      id: 3,
      completed: false,
      date: '11/10/23',
      timeType: 'MAÑANA',
      start_time: '10:00',
      end_time: '11:00',
    },
    {
      id: 4,
      completed: false,
      date: '11/10/23',
      timeType: 'MAÑANA',
      start_time: '11:00',
      end_time: '12:00',
    },
    {
      id: 5,
      completed: false,
      date: '11/10/23',
      timeType: 'MAÑANA',
      start_time: '08:00',
      end_time: '09:00',
    },
    {
      id: 6,
      completed: false,
      date: '11/10/23',
      timeType: 'MAÑANA',
      start_time: '09:00',
      end_time: '10:00',
    },
    {
      id: 7,
      completed: false,
      date: '11/10/23',
      timeType: 'MAÑANA',
      start_time: '10:00',
      end_time: '11:00',
    },
    {
      id: 8,
      completed: false,
      date: '11/10/23',
      timeType: 'MAÑANA',
      start_time: '11:00',
      end_time: '12:00',
    },
  
    {
      id: 9,
      completed: false,
      date: '11/10/23',
      timeType: 'TARDE',
      start_time: '16:00',
      end_time: '17:00',
    },
    {
      id: 10,
      completed: false,
      date: '11/10/23',
      timeType: 'TARDE',
      start_time: '17:00',
      end_time: '18:00',
    },
    {
      id: 11,
      completed: false,
      date: '11/10/23',
      timeType: 'TARDE',
      start_time: '18:00',
      end_time: '19:00',
    },
    {
      id: 12,
      completed: false,
      date: '11/10/23',
      timeType: 'TARDE',
      start_time: '19:00',
      end_time: '20:00',
    },
    {
      id: 13,
      completed: false,
      date: '11/10/23',
      timeType: 'TARDE',
      start_time: '20:00',
      end_time: '21:00',
    },
    {
      id: 14,
      completed: false,
      date: '11/10/23',
      timeType: 'TARDE',
      start_time: '21:00',
      end_time: '22:00',
    },
    {
      id: 15,
      completed: false,
      date: '11/10/23',
      timeType: 'TARDE',
      start_time: '22:00',
      end_time: '23:00',
    },
    {
      id: 16,
      completed: false,
      date: '11/10/23',
      timeType: 'TARDE',
      start_time: '23:00',
      end_time: '00:00',
    },
  ];